### ISSUE TITLE
Page fault on Linux 6.4.1 x86_64

### ISSUE THREAD

**Issue by conqp** [deadblackclover/pc-beeper#4]
I get a page fault using this library on my Linux machine:

`Cargo.toml`
```toml
[package]
name = "beep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pc-beeper = "0.1.1"
```
`src/main.rs`
```rust
use pc_beeper::Speaker;

fn main() {
    let mut speaker = Speaker::new();
    speaker.beep(1000, 10);
}
```
Build:
```
$ LANG=C cargo +nightly build --release 
   Compiling rustversion v1.0.13
   Compiling bit_field v0.10.2
   Compiling bitflags v1.3.2
   Compiling volatile v0.4.6
   Compiling x86_64 v0.14.10
   Compiling pc-beeper v0.1.1
   Compiling beep v0.1.0 (/home/neumann/beep)
    Finished release [optimized] target(s) in 0.94s
```
Run:
```
$ LANG=C ./target/release/beep 
Speicherzugriffsfehler (Speicherabzug geschrieben)
139 ✗ neumann@workstation ~/beep $ 
```
System:
```
$ uname -a
Linux workstation 6.4.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 01 Jul 2023 16:17:21 +0000 x86_64 GNU/Linux
```
